export const STORE_NAME = '@URI';

export const STORE_KEYS = {
  AUTHENTICATED: STORE_NAME + '@AUTHENTICATED',
  THEME: STORE_NAME + '@THEME',
  USER_DETAILS: STORE_NAME + '@USER_DETAILS',
  USER_PROFILE: STORE_NAME + '@USER_PROFILE',
  USER_TOKENS: STORE_NAME + '@USER_TOKENS',
  REMEMBER_ME_EMAIL_KEY: STORE_NAME + '@REMEMBER_ME_EMAIL',
  REMEMBER_ME_PASSWORD_KEY: STORE_NAME + '@REMEMBER_ME_PASSWORD',
  USER_SUBSCRIPTION_PLAN_TYPE: STORE_NAME + '@USER_SUBSCRIPTION_PLAN_TYPE',
};
