import { BackendUrlEnum } from '@/src/models/enum-models/BackendUrlEnum';
import { RouteHelper } from '../../helpers/RouteHelper';

const URI_INSIGHTS_PATH = BackendUrlEnum.INSIGHTS + '/social-media';

type ISocialMediaAgentApi =
  | 'connectFacebookToken'
  | 'initiateConnection'
  | 'pendingConnection'
  | 'finalizeConnection'
  | 'getConnections'
  | 'disconnectPlatform'
  | 'generateContent'
  | 'uploadUserContent'
  | 'generateStoryboard'
  | 'generateVideoFromStoryboard'
  | 'videoJob'
  | 'refineContent'
  | 'approveContent'
  | 'denyContent'
  | 'deleteDraft'
  | 'contentCalendar'
  | 'scheduledContent'
  | 'autoGenerateSettings'
  | 'autoGenerateTrigger'
  | 'autoGenerateConnectInsights'
  | 'calendarPlan'
  | 'calendarPlanGenerate'
  | 'calendarDayBase'
  | 'calendarToday'
  | 'mergeVideoJob'
  | 'videoDrafts'
  | 'generateStoryboardFrames'
  | 'storyboardFrameJob'
  | 'publishVideoDraft'
  | 'videoPublishJob'
  | 'extractImageText'
  | 'uploadCustomFont'
  | 'analyzeCustomFont'
  | 'generateBlog'
  | 'getBlogDrafts'
  | 'getBlogDraft'
  | 'agentChat'
  | 'agentChatHistory'
  | 'clearAgentChat'
  | 'agentChatStream'
  | 'agentChatUpload'
  | 'editVideo'
  | 'editVideoJob'
  | 'polishVideo'
  | 'polishVideoJob'
  | 'polishVideoRestyle'
  | 'videoPolishStyles'
  | 'writingDnaQuiz'
  | 'writingDna'
  | 'generateBlogPost'
  | 'blogPosts'
  | 'blogPostById'
  | 'blogPostFeedback'
  | 'blogPostPublish'
  | 'agency'
  | 'agencyRoster'
  | 'agencyBrands'
  | 'agencyBrandsDuplicate'
  | 'agencyBrandById'
  | 'agencyMembers'
  | 'agencyMemberById'
  | 'agencyMemberBrand'
  | 'agencyWalletTopup'
  | 'agencySettings'
  | 'agencyReportPortfolio'
  | 'agencyReportBrand'
  | 'produceVideo'
  | 'produceVideoJob'
  | 'produceVideoStartRender'
  | 'generateVideoCaption'
  | 'multiClipStart'
  | 'multiClipJob'
  | 'multiClipReorder'
  | 'multiClipDropClip'
  | 'multiClipStitch'
  | 'multiClipDraftScript'
  | 'multiClipApproveScript'
  | 'multiClipReset'
  | 'multiClipUpdateClip'
  | 'submagicProduce'
  | 'submagicJob';

const rawSocialMediaAgentRoutes: Record<ISocialMediaAgentApi, string> = {
  connectFacebookToken: '/connect/facebook/token',
  initiateConnection: '/connect/initiate',
  pendingConnection: '/connect/pending',
  finalizeConnection: '/connect/finalize',
  getConnections: '/connections',
  disconnectPlatform: '/connections/account',
  generateContent: '/generate-content',
  uploadUserContent: '/upload-user-content',
  generateStoryboard: '/generate-storyboard',
  generateVideoFromStoryboard: '/generate-video-from-storyboard',
  videoJob: '/video-job',
  refineContent: '/refine',
  approveContent: '/approve',
  denyContent: '/deny',
  deleteDraft: '/drafts',
  contentCalendar: '/content-calendar',
  scheduledContent: '/scheduled',
  autoGenerateSettings: '/auto-generate/settings',
  autoGenerateTrigger: '/auto-generate/trigger',
  autoGenerateConnectInsights: '/auto-generate/connect-insights',
  calendarPlan: '/content-calendar/plan',
  calendarPlanGenerate: '/content-calendar/plan/generate',
  calendarDayBase: '/content-calendar/plan',
  calendarToday: '/content-calendar/today',
  mergeVideoJob: '/merge-video-job',
  videoDrafts: '/video-drafts',
  generateStoryboardFrames: '/generate-storyboard-frames',
  storyboardFrameJob: '/storyboard-frame-job',
  publishVideoDraft: '/publish-video-draft',
  videoPublishJob: '/video-publish-job',
  extractImageText: '/extract-image-text',
  uploadCustomFont: '/upload-custom-font',
  analyzeCustomFont: '/analyze-custom-font',
  generateBlog: '/generate-blog',
  getBlogDrafts: '/blog-drafts',
  getBlogDraft: '/blog-drafts/{draft_id}',
  agentChat: '/agent/chat',
  agentChatHistory: '/agent/chat/history',
  clearAgentChat: '/agent/chat/history',
  agentChatStream: '/agent/chat/stream',
  agentChatUpload: '/agent/chat/upload',
  editVideo: '/edit-video',
  editVideoJob: '/edit-video-job',
  polishVideo: '/polish-video',
  polishVideoJob: '/polish-video-job',
  polishVideoRestyle: '/polish-video-restyle',
  videoPolishStyles: '/video-polish-styles',
  // Writing DNA Blog Generator
  writingDnaQuiz: '/blog/writing-dna/quiz',
  writingDna: '/blog/writing-dna',
  generateBlogPost: '/blog/generate',
  blogPosts: '/blog/posts',
  blogPostById: '/blog/posts/{blog_id}',
  blogPostFeedback: '/blog/posts/{blog_id}/feedback',
  blogPostPublish: '/blog/posts/{blog_id}/publish',
  // Agency Accounts
  agency: '/agency',
  agencyRoster: '/agency/roster',
  agencyBrands: '/agency/brands',
  agencyBrandsDuplicate: '/agency/brands/duplicate',
  agencyBrandById: '/agency/brands/{brand_id}',
  agencyMembers: '/agency/members',
  agencyMemberById: '/agency/members/{member_id}',
  agencyMemberBrand: '/agency/members/{member_id}/brands/{brand_id}',
  agencyWalletTopup: '/agency/wallet/topup',
  agencySettings: '/agency/settings',
  agencyReportPortfolio: '/agency/reports/portfolio',
  agencyReportBrand: '/agency/reports/brand/{brand_id}',
  produceVideo: '/produce-video',
  produceVideoJob: '/produce-video-job',
  produceVideoStartRender: '/produce-video-job',
  generateVideoCaption: '/generate-video-caption',
  multiClipStart: '/multi-clip/start',
  multiClipJob: '/multi-clip/job',
  multiClipReorder: '/multi-clip/job',
  multiClipDropClip: '/multi-clip/job',
  multiClipStitch: '/multi-clip/job',
  multiClipDraftScript: '/multi-clip/job',
  multiClipApproveScript: '/multi-clip/job',
  multiClipReset: '/multi-clip/job',
  multiClipUpdateClip: '/multi-clip/job',
  submagicProduce: '/submagic-produce',
  submagicJob: '/submagic-job',
};

export const socialMediaAgentRoutes: Record<ISocialMediaAgentApi, string> = RouteHelper.createRoutes(
  URI_INSIGHTS_PATH,
  rawSocialMediaAgentRoutes
);
